/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src\components\modelcomponent\wardrobe.glb --output src\components\modelcomponent\wardrobe --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    base_2_Mat_0_1: THREE.Mesh
    base_2_Mat_0_2: THREE.Mesh
    base_2_Mat_0_3: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    door: THREE.MeshStandardMaterial
    handle: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>
type WardrobeProps = JSX.IntrinsicElements['group'] & {
  showDoor: boolean
  showHandle: boolean
}

export function Wardrobe({ showDoor, showHandle, ...props }: WardrobeProps) {
  const { nodes, materials } = useGLTF('/wardrobe.glb') as GLTFResult
  const bbox = new THREE.Box3().setFromObject(nodes.base_2_Mat_0_2);
  const size = bbox.getSize(new THREE.Vector3());
  return (
    <group {...props} dispose={null}>
      <group position={[1, 0.5, -7.7]} scale={0.025}>
        <mesh geometry={nodes.base_2_Mat_0_1.geometry} material={materials.material} />
        {showDoor && (
        <mesh geometry={nodes.base_2_Mat_0_2.geometry} material={materials.door} /> 
      )} 
            {showHandle && (<mesh geometry={nodes.base_2_Mat_0_3.geometry} material={materials.handle} />
     )} 
     <Html position={[size.x / 2, size.y, 0]} center>
        <div style={{ background: 'white', padding: '2px', borderRadius: '3px', fontSize: '12px' }}>
          {`Width: ${size.x.toFixed(2)}m`}
        </div>
      </Html>
      <Html position={[0, size.y / 2, size.z / 2]} center>
        <div style={{ background: 'white', padding: '2px', borderRadius: '3px', fontSize: '12px' }}>
          {`Height: ${size.y.toFixed(2)}m`}
        </div>
      </Html>
      <Html position={[0, size.y, size.z / 2]} center>
        <div style={{ background: 'white', padding: '2px', borderRadius: '3px', fontSize: '12px' }}>
          {`Depth: ${size.z.toFixed(2)}m`}
        </div>
      </Html>
      </group>
    </group>
  )
}

useGLTF.preload('/wardrobe.glb')
